### ISSUE TITLE
Error unpacking grr-server_3.4.6-7_amd64.deb

### ISSUE THREAD

**Issue by AMON206** [google/grr#1031]
I am running on Ubuntu 20.04.6
I  installed GRR from release DEB and currently trying to install grr-server_3.4.6-7
After creating the databases on mysql and modifying the max_allowed_packet size as the docs says and when installing the .deb package it doesn't prompt me for any thing for the sql database info (such as user and password ..etc)
and it gives me the following error :
###################################

from grr_response_server.distro_entry import ConfigUpdater
ModuleNotFoundError: No module named 'grr_response_server'
dpkg: error processing package grr-server (--configure):
 installed grr-server package post-installation script subprocess re
turned error exit status 1
Setting up locate (4.7.0-1ubuntu1) ...
Processing triggers for man-db (2.9.1-1) ...
Errors were encountered while processing:
 grr-server
E: Sub-process /usr/bin/dpkg returned an error code (1)

#####################################

And now when i try to apt install anything it gives me the same error as above

I tried to force the installation but the same problem occurs

**Comment by mbushkov** [comment]
Hi @AMON206 
I double-checked the instructions https://grr-doc.readthedocs.io/en/latest/installing-grr-server/from-release-deb.html on Ubuntu 22 - the server deb installs and works as expected.

Most likely the issue is due to the fact that you're trying to install it on Ubuntu 20. GRR server deb package is built for Ubuntu 22 only. Please try using this version of Ubuntu.
