### ISSUE TITLE
Rekall Results Broken

### ISSUE THREAD

**Issue by pidydx** [google/grr#107]
In the latest version of the server and the 3.0.0.3 client template we are having problems with AnalyzeMemory.  We will run rekall modules like psxview and it will return 0 results or it will cause memory limit exceeded errors.

**Comment by scudette** [comment]
The latest server must work with client version 3.0.0.5 which has the
latest Rekall in it.

**Comment by pidydx** [comment]
Can you post the 3.0.0.5 templates?

**Comment by grrrrrrrrr** [comment]
We have pushed the 3.0.0.5 Windows templates to the download section and also prebuilds for Linux and OSX.

You can use those prebuilds but Rekall will not work with them. This is not a big deal since 3.0.0.3 doesn't support Rekall on Linux/Mac either but we'd like to have the final 3.0.0.5 (or maybe .6 then) to support Rekall on all platforms.

**Comment by pidydx** [comment]
Thanks!  I have it working with Win 3.0.0.5.
