### ISSUE TITLE
Is it possible to generate MD5 hashes of running processes?

### ISSUE THREAD

**Issue by djmundus** [google/grr#129]
Is there any way for me to see the MD5 hash of running processes?  That would be an excellent feature...

Thanks.

C

**Comment by scudette** [comment]
What does that mean? 

Do you want to hash the executable on disk for running processes? if so you just do a pslist and hash the executables that come back.

Do you want to dump executables from memory? in that case you can use procdump and rekall to dump them from memory - but note that the hash of processes in memory is not useful to compare because it is different than on disk and also due to runtime modifications like relocations different between different executions of the same binary. Also memory is unlikely to contain all the pages of running binaries since the OS will only load executing pages on demand.

Also BTW MD5 is broken SHA256 is the new hotness :-)

**Comment by djmundus** [comment]
I'm more of a SEIM guy than a forensics guy, so a lot of this is new to me...

I was hoping to find functionality similar to Carbon Black where every time a process or library loads, a log message is generated that contains the hash.  I was hoping to compare that against the collective intelligence framework, which only supports MD5s.

SHA256 may be sexy, but I've definitely found it to be "fuzzy" in a number of vendor implementations.  Such that a matching MD5 hash for a file on VirusTotal does not produce a matching SHA256 hash.

**Comment by scudette** [comment]
GRR does not hook or register any client side event handlers so we cant know when a process loads or runs. We can only run passive checks - like list processes, hash files etc.

You can run the list processes flow and there is a checkbox there to "download binaries". This is basically the same as hashing since GRR deduplicates file by hashing them. The hashes will be sent back for all running processes (but only the .exe afaik - no dlls). If the the server has not seen this hash before, the data will be sent (thats kind of what you want most of the time anyway).

I believe that we also do md5 as well as all the other hashes according to this
https://github.com/google/grr/blob/master/lib/aff4_objects/filestore.py#L259

So you could conceivable just run this flow on all your clients at once and then just check the hashes in the filestore.
