### ISSUE TITLE
Datastore growth

### ISSUE THREAD

**Issue by pidydx** [google/grr#135]
We have started to hit performance issues related to datastore growth now.  The problem is that in order to effectively retrieve this key/value structured data from MySQL it kinda requires fairly large indexes.  Sitting at in the neighborhood of 1 billion rows has caused the index to grow extremely large.  

Most of this data doesn't need to be retained so having an effective way to remove old flow results, hunt results, dead clients, unused blobs, and trimming client vfs data is going to be critical.  

In the short term we can throw more more memory at it and potentially faster drives, but short of datastore management stuff this is going to require periodic full resets.

**Comment by scudette** [comment]
In the short term maybe a good solution is to run a script to archive the data to a disk. If we need to restore the data back this should be easy and it will relieve the immediate pressure off the data base. We can think of refining this process in future but this approach I think will give the biggest gain.

Essentially all that is required is to run over all the blobs and archive them - there is already a very easy utility for this here:

https://github.com/google/grr/blob/master/lib/serialize.py#L10

but maybe we can make it slightly more efficient (It would dump the content of the blob encoded in base64 in the yaml file).

This can be done for all other objects. If they objects are older than a certain age - just dump to disk  If there is an external reference to it, it might break - or maybe we can find a system which automatically brings in the yaml file from "offline storage".

Happy to have a go at a quick script.

**Comment by destijl** [comment]
IIUC sean is saying the overall row count is the major problem here, more than total data size, so archiving all the blobs may not help enough (although we definitely need that functionality too).  I suspect some big scans through the registry and disk have produced many statentries stored in the client space.  Sean started some COUNT queries to figure out where the majority of the rows were, but they ran for a very long time and didn't finish.  @pidydx It might be good to sample some representative clients and check if they do have lots of statentries in the vfs.

If that is the problem, deleting the client space will fix it at the expense of losing lots of history. That's still slightly better than a full database reset because you retain the blobs, so save on future bytes being sent from the clients.

**Comment by pidydx** [comment]
Ideally we could have a mix of things in datastore management.  Being able to cleanup stuff manually or age it out.  My thought for dealing with history, particularly with dead clients is to apply a label (label management also a thing) to the ones we want to keep and then let a cron job just go through and scrub out client that haven't checked in for 90 days.  Being able to scrub out hunt results would be nice.  Flows and client space is a little more difficult, but a similar system of labeling clients to be retained while letting a cron job come through and reset individual clients to an original state or perhaps a threshold of only keep the last X entries and/or X days for any stat item.  There is also a later problem of privacy/retention stuff of being able to age things out.

It would also be nice to have a better idea of what parts of the datastore are getting full.  
When using the system to go hunting for things using Artifacts you can wind up collecting a lot of data that you just want to export, analyze, and recollect at some later point.  The history of the status of that data kinda needs to be retained outside of GRR since you also want to know any analyst determinations on the data.

**Comment by pidydx** [comment]
Closing as this is in progress and has been broken into specific pieces.
