### ISSUE TITLE
Queue queue_timer seems full

### ISSUE THREAD

**Issue by pidydx** [google/grr#137]
This was the weird error message we discussed in a previous meeting.  Still not sure how to reliably reproduce.

![screen shot 2015-03-11 at 6 14 34 pm](https://cloud.githubusercontent.com/assets/8451350/6610313/acb069de-c81a-11e4-8f4e-67f7d620d663.png)

**Comment by scudette** [comment]
So this is a GUI bug - the GUI has message queues which are events some things publish to and other things can listen to the event. Due to the way the DOM is manipulated we attach listeners to the DOM elements that want to know when something changed (e.g. the right pane is listening for click events on the tree).

Sometimes the queues get full due to a bug - listeners are accumulating but are not properly removed when the DOM is removed.

Thats what this message is about. The queue which is full is called "timer" and it is messaged every 500ms:
https://github.com/google/grr/blob/96f0e5bb863318867502992dc6c7542731c1a9dd/gui/static/javascript/grr.js#L150

Looks like there is one place using it:
https://github.com/google/grr/blob/2547f3c5b3419cc9ee94a46bcac426d59cc4e1a5/gui/static/javascript/plugins/searchclient.js#L192

which is rendering the HostTable for the search. If this listener is not removed, it will probably accumulate and trigger this error after about 50 searches.

I think this code is migrating to angular real soon now so not worth debugging - with angular the GUI will just get slower when watchers accumulate instead.

**Comment by pidydx** [comment]
Sounds good.  I just remember we talked about this, but no one was really sure exactly what the error was at the time.
