### ISSUE TITLE
Cannot add labels in latest GRR AdminUI

### ISSUE THREAD

**Issue by pidydx** [google/grr#161]
Attempting to add a label in the UI triggers background activity, but the popup never goes away.  Searching for the label gives no results and searching for the client shows no labels.

**Comment by pidydx** [comment]
I can AddLabels/RemoveLabels correctly from console and those labels do appear in on the host in the search view.  I also cannot remove a label from the UI.

**Comment by mbushkov** [comment]
Hi Sean! Just in case - try cleaning the browser cache or force reloading the page (Shift+Reload) - this kind of behaviour is sometimes caused by stale Javascript files.

Can you possibly look at what Chrome does when you try to add a label? You can do this by opening the Developer Tools and going to Network tab. AdminUI logs will greatly help as well - most probably you'll see an exception somewhere.

**Comment by pidydx** [comment]
Good news! It wasn't a cache problem, but I was 1 commit behind on my test branch.  Sorry for the false alarm. :)
