### ISSUE TITLE
Using AnalyizeClientMemory

### ISSUE THREAD

**Issue by Josh-white** [google/grr#241]
I know I am missing something simple but I cant quite figure it out. I am trying to use the analyizeclientmemory flow and its keeps giving me an error about a string. I have attached a picture of my problem. Can someone please help me out with this. thanks in advance .
![grr-question-picture](https://cloud.githubusercontent.com/assets/11305256/9081312/df1d58b6-3b63-11e5-98b1-d49b6398e000.png)

**Comment by mbushkov** [comment]
Hi Josh,
Do I understand correctly, that you're using latest GRR version from the
GitHub repo? If so, can you please sync with the latest changes (we
submitted bunch of fixes just recently) and try again? After updating
please clear your browser cache, otherwise the frontend UI may still use
the old cached javascript files.

Cheers,
Misha

**Comment by Josh-white** [comment]
I think I am using the latest version I just downloaded it from github last week. We will do an apt-get update for grr and I will get back with you to let you know if any of this resolves my issue. Thanks for getting back to me so quick too.

**Comment by mbushkov** [comment]
Hi Josh,
No problem and please tell me if the bug persists after you update the
server.

Cheers,
Misha

**Comment by Josh-white** [comment]
Hey Misha,

I am pretty sure we are up to date we are running version 3.0.0.7. 

We just installed the OS and GRR on this server a few days ago. If there is something that I can try I will give it a shot and send screen shots of the results. Im going to start going through the HTML and see if I can find the field for this flow. Thanks again for everything.

Josh

**Comment by mbushkov** [comment]
I checked the 3.0.0.7 release and I see that includes necessary UI bugfixes.
Going through HTML may be problematic, because GRR UI uses Angular
javascript framework, so you have to be familiar with it to dig through the
code.

Can you please open Chrome's developer console (
https://developer.chrome.com/devtools/docs/console) and check whether there
are some error messages there?

It's strange that there's no input controls for "Args" on the screenshot
that you sent. Just checking one more time (because this is a typical
problem) - you tried clearing the browser cache already, right?

Cheers,
Misha

**Comment by Josh-white** [comment]
Misha,

Yea as I was going through it I was using Firefox and have it clear cache every time I close the browser but I will double check that again also. I will get back to you here shortly.

Thanks Josh ; )

**Comment by Hookapelli** [comment]
Misha,
Here's the error.
![issue1](https://cloud.githubusercontent.com/assets/13619157/9084348/74964f58-3b7b-11e5-978a-91a3eb8dcbab.jpg)

**Comment by Hookapelli** [comment]
Here is the location I think the file should be in...  but it is absent. 
![issue2](https://cloud.githubusercontent.com/assets/13619157/9084456/8d9c0014-3b7c-11e5-8cc4-8bc00cbc65dc.jpg)

**Comment by mbushkov** [comment]
This is ok - i.e. this is expected. I'll look into your problem. Right now,
it's not obvious why it fails.

One thing - can you start a hunt with this flow? Will starting a hunt fail
as well?

Cheers,
Misha

**Comment by Josh-white** [comment]
![first_hunt_pic](https://cloud.githubusercontent.com/assets/11305256/9085447/7ef1775c-3b85-11e5-8999-4fa969bacd95.png)
![second_hunt_pic](https://cloud.githubusercontent.com/assets/11305256/9085451/831ceeba-3b85-11e5-85af-94ca2fbbd497.png)


I have attached two pictures. It looks like the hunt is running with a PSList plugin. I will post if the results come back. But at least we didnt get the same error so now at least I have a work around. Thanks for that until we can get this flow fixed.

**Comment by mbushkov** [comment]
So it seems that the GRR's dpkg version is slightly behind the latest
version on GitHub and/or Docker. We'll rebuild the GRR server deb and
reupload it. As soon as it's done you'll be able to apt-get update and the
bug will most probably go away. ETA for the server rebuild is beginning of
next week.

Cheers,
Misha

**Comment by destijl** [comment]
I have built a new server deb and uploaded it here:
https://drive.google.com/open?id=0B1wsLqFoT7i2RUVsSnFpdi1lWFU

If you run the install script again on a new system it will use the new version. If you upgrade the existing server make sure you uninstall the previous package and check it removed all the code. You definitely want to keep your config files under /etc/ (maybe back them up somewhere first).  Make sure you do a hard refresh in the UI when re-testing.
