### ISSUE TITLE
DownloadMemoryImage against a Linux box tries first load a memory driver despite /proc/kcore being present

### ISSUE THREAD

**Issue by parkisan** [google/grr#247]
We should first attempt AnalyzeClientMemory(ewfacquire), and if it fails try the driver approach instead.

**Comment by cybercuffs** [comment]
1- The AnalyzeClientMemory gives the error as:
  This kcore file is too small (4096 bytes) and likely invalid for memory analysis. You may want to use pmem instead

2- But I get the following error when I use the SEND TO SOCKET option.  
  Can't start flow MemoryCollector:
Unable to find a driver for client.

**Comment by scudette** [comment]
Normally we try to use /proc/kcore on linux because its easier to get memory access (you dont need a driver) but some linux distributions disable the kcore device (only the first page is available). On these distributions you need to load the pmem driver instead. The current GRR architecture requires the driver to be pushed from the server but on linux this is pretty difficult because you need to compile the pmem driver for the target before hand (so you kind of have to build a library of pmem drivers for all your deployed hosts - and keep that up to date).

Currently there is no easy way to analyze linux systems with GRR that turned off kcore access. It is kind of possible but difficult - you need to pre-compile the pmem driver and push it to the machine and load it. You would probably need to write code to manage this library of drivers on the GRR server, decide exactly which version is needed and then take care of loading the right driver yourself.

**Comment by cybercuffs** [comment]
Thanks for the detailed information @scudette.

**Comment by destijl** [comment]
This is now fixed.
