### ISSUE TITLE
Hex string literals no longer work in FileFinder

### ISSUE THREAD

**Issue by destijl** [google/grr#263]
To search for a mach-o you used to be able to use FileFinder with a string literal:

\xca\xfe   etc.

But with the new UI this gets escaped:
```
{"runner_args":{"flow_name":"FileFinder","output_plugins":[]},"flow_args":{"paths":["/usr/bin/file"],"conditions":[{"modification_time":{"max_last_modified_time":null},"condition_type":"CONTENTS_LITERAL_MATCH","contents_literal_match":{"literal":"\\xca\\xfe","mode":"FIRST_HIT","start_offset":0,"length":10737418240,"bytes_before":10,"bytes_after":10,"xor_in_key":0,"xor_out_key":0}}]}}:
```
and never un-escaped. In the old UI we used to unescape with .decode("string_escape") for LiteralExpression rdf values:
https://github.com/google/grr/blob/69c81624c281216a45c4bb88a9d4e4b0613a3556/gui/plugins/flow_management.py#L991
https://github.com/google/grr/blob/919a844c396136bd49c457f18d853dd10b79abed/gui/plugins/forms.py#L329

but the new UI doesn't do this. And it's actually a more general problem of trying to deliver bytes via JSON without encoding.

After discussing with @scudette we think we should explicitly force the angular code to encode it 
in one of three ways:

- as a unicode string, then we decode it into utf8
- as an object {encoding: "hex", data: "CAFEBABE"}
- or {encoding: "string", data: "\xCA\xFE"}

and it should be possible for the user to toggle the string literal field between each of these inputs so it's explicit about what they are sending (probably a new directive for RDFBytes and LiteralExpression types).

This also means that if you choose "hex" input the angular code could strip whitespace and check you have full bytes specified, so that you can just paste a string in from your hex editor like:

```
4D 5A 90 00  03
```

and it would do the right thing, rather than having to mess around adding \x's and deleting spaces.

**Comment by scudette** [comment]
The problem is a fundamental issue with a Restful API - Json can not represent binary data. So we must encode the binary data in some way, and then decode it in the API renderer. This code 

https://github.com/google/grr/blob/master/gui/http_api.py#L185

Copies all the json data into the Semantic Protobuf - however since JSON can not represent bytes, for bytes fields an additional level of encoding should occur (as Greg mentioned before).

As well as this change we also must implement a directive that allows the user to input data in the above mentioned ways (hex, escaped, string etc). I think we could also add additional encodings which would be super useful like UTF16.

**Comment by destijl** [comment]
Now fixed
