### ISSUE TITLE
Tag files matched in NSRL

### ISSUE THREAD

**Issue by keithtyler** [google/grr#298]
If a flow comes across a match in the NSRL, it would be good if GRR tagged it with the metadata matched in the NSRL since it contains known good and known bad files.

**Comment by pettai** [comment]
+1

**Comment by darrenbilby** [comment]
Out of interest, where would you like to see this information? There seems to be two ways to solve this:

1. Have automatic event handlers that see every new file that comes in and adds additional metadata, probably asynchronously. This requires having some extensible attributes on the file-like AFF4 objects because it would make sense to expand it over time, NSRL, Virustotal etc. This of course also raises the issue of how you keep the data up to date, e.g. no VT hits when you collected the file, but 3 days later when you are looking there might be.

2. Alternatively, we just do it as a UI component, so when you are looking at a file it has a tab for analysis, which when opened does the queries and shows the data live. 

The latter is a lot simpler, but precludes making automated decisions based on the data.

**Comment by mutedmouse** [comment]
I could see the value in being able to choose an offline hash set (knows
bad) in the event you are on a closed network as well gentlemen.

**Comment by grrrrrrrrr** [comment]
We decided a while back that the NSRL doesn't provide enough value for the maintenance work it requires to keep the hashes up to date and dropped support. This is obsolete.
