### ISSUE TITLE
Feature request: Warn about plugins that will not work for tasked agents

### ISSUE THREAD

**Issue by 0xdabbad00** [google/grr#301]
With regard to #269, some commands will not work for all agents.  This can be confusing.  The UI should warn users that they are attempting to do something that is not possible.

**Comment by scudette** [comment]
This is kind of hard to do- the server has no idea if the client can or can not do the action until it tries. The GUI can show a warning but what does it mean? Would you expect the user to cancel the flow? If you expect the user to run the flow anyway and just know that it might not work - this doesnt actually change anything from the current situation (ie you need to wait for the client to fail the request).

Note that the artifact system tries to help a bit with this because most artifacts have a supported_os field, or offer different implementations for different os's.

**Comment by destijl** [comment]
As michael says knowing all the capabilities of the client is a hard problem when you have multiple versions deployed, and especially for rekall and artifacts since tons of functionality is bundled under single server-side flows. 

But https://github.com/google/grr/issues/269 was an error on our part, it always should have been under advanced. The rough contract we have with users is that flows visible in basic UI mode should be reliable. Stuff under advanced is hidden for a reason. See:
https://github.com/google/grr-doc/blob/master/user_manual.adoc#grr-ui-modes

I'm going to close this since I think we're covering most of the problem space with the basic/advanced split. We can revisit in the future if it becomes a big problem.
