### ISSUE TITLE
Behavior of "use_tsk" in artifact collector flow for Windows Regitry artifacts

### ISSUE THREAD

**Issue by joachimmetz** [google/grr#306]
Can someone confirm or deny that when running an artifact collection for Windows Registry artifacts and ticking on "use_tsk" that the collection will have the client use the TSK VFS handler and not the Registry one?

**Comment by scudette** [comment]
I would not expect this to be true. AFAIK grr has no way to parse the raw
registry hive at the moment which is what you would need to do. I would
suggest to download the registry files and parse then externally.
Technically you can use rekall to parse the raw hives but that is not
tested.
Am 28.11.2015 8:24 vorm. schrieb "Joachim Metz" <notifications@github.com>:

**Comment by joachimmetz** [comment]
Let's sync on this next week, I'm getting some error messages that make wonder about the behavior

**Comment by scudette** [comment]
I see. I'm not saying things are are actually working like this, but that
this is what I would expect would happen. But it's possible there is a bug
where selecting use tsk forces the path type to tsk even though it's
supposed to be a reg artifact. This is entirely possible.

Can't check right now because laptop seems broken.
Am 28.11.2015 8:33 vorm. schrieb "Joachim Metz" <notifications@github.com>:
