### ISSUE TITLE
install script fails

### ISSUE THREAD

**Issue by pamisano** [google/grr#320]
I am trying to install on the SANS SIFT distro which is Ubuntu base.  I get the following error when the grr_config_updater runs:

  File "/usr/local/lib/python2.7/dist-packages/rekall/entities/query/analyzer.py", line 29, in <module>
    from efilter import engine
ImportError: cannot import name engine
#########################################################################################
FAILURE RUNNING: grr_config_updater initialize
#########################################################################################
sansforensics@siftworkstation:~/Downloads$

Any assistance would be greatly appreciated!!!

**Comment by scudette** [comment]
It is possible that somehow you have installed a later version of efilter which is not compatible with Rekall 1.4.1. If you check the requirements.txt file you can see we need exactly this version:

https://github.com/google/grr/blob/master/requirements.txt#L30

```
efilter==1438631774
```

Sometimes if people just do `pip install efilter` it will install the latest which will break - since efilter is not backward compatible at this stage.

Make sure you have the correct version by issuing `pip freeze | grep efilter`. If you have a later version just downgrade: `pip install efilter==1438631774`

**Comment by pamisano** [comment]
pip freeze | grep efilter displays: efilter==1438631774

**Comment by scudette** [comment]
Did you install a later version of rekall maybe?

```rekall --version```

What sometimes happens too is that that are some old files from rekall around which are accidentally getting picked up. Search for efilter* in /usr/local/lib/python2.7/dist-packages/rekall/  or 
/usr/lib/python2.7/dist-packages/rekall/

Failing this you should be able to see where it is trying to pick efilter up from using the -v flag to python:

```
$ python -v -c "import rekall" 2>&1 | grep efilter
# zipimport: found 104 names in /home/scudette/Dev/local/lib/python2.7/site-packages/efilter-1450268920-py2.7.egg
# zipimport: found 104 names in /home/scudette/Dev/lib/python2.7/site-packages/efilter-1450268920-py2.7.egg
```

**Comment by mutedmouse** [comment]
Sift typically comes with a newer version of rekall. Best to install grr
first on Ubuntu and then install the sift toolkit.  Then downgrade rekall
as per the requirements if this level 9f dual functionality is what you are
aiming for.

Efilter seems to change quite frequently and unfortunately in a way
detrimental to grr operational success.

**Comment by scudette** [comment]
This is largely a GRR issue - python packages (like GRR) should be installed in a virtualenv and not interact with any system installed packages. Whats happening here is that two different versions of rekall are fighting for different versions of efilter they need.  I think we need to update the install script to do that.

Try to search for any installed version if rekall anywhere on the system and remove it and then reinstall.

**Comment by velpavlov** [comment]
Instead of creating a new issue, I figure I tag to this existing one. For any new installs... there is an error in the requirements.txt due to a version change for distrom3, The current requirements.txt version LINE 12 reads "distorm3==3.3.0" when the newest version is 3.3.1. Edit of the locally downloaded requirements.txt fixes the problem without the need to manually install the package. Heads up.

**Comment by grrrrrrrrr** [comment]
Hey,

Thanks for the report! Is this really failing for you? In the end, it should just install the old version and use that. Anyways, there is nothing for us to do here since newer versions of GRR/Rekall don't depend on distorm anymore and the current requirements doesn't list this dependency at all. Closing.

Cheers,
-Andy
