### ISSUE TITLE
Implement elasticsearch output plugin

### ISSUE THREAD

**Issue by destijl** [google/grr#374]
Filing this so people can track and subscribe. The implementation of an elasticsearch output plugin should be fairly simple using the BigQuery output plugin as a guide:

http://grr-response.blogspot.com/2015/11/using-bigquery-to-analyze-data.html
https://github.com/google/grr/blob/master/grr/lib/output_plugins/bigquery_plugin.py

We don't have plans to write this in Q2 2016, but we might consider it for next quarter depending on our other priorities.

**Comment by bwagner5** [comment]
I've got some cycles to start working on this. Having some troubles getting the latest version to build though... Can someone take a look at: https://groups.google.com/forum/#!topic/grr-dev/_FdWyIwk9vs  

First, I was getting dependency errors because of Rekall (which has been fixed), then `IOError: Unable to find resource grr/config/grr-server.yaml`, which seems to be a regression from previous versions, but I was able to just copy the config file into the right spot, and now I'm getting the Context Error.

**Comment by destijl** [comment]
You don't want to do dev inside a docker container, follow the pip install instructions:
https://github.com/google/grr-doc/blob/master/installfrompip.adoc#installing-grr-server-for-dev-ie-tracking-head

**Comment by gio33gio** [comment]
Hi desijl

I've managed to install GRR and it's brilliant. everything works fine and I've tried to use it for my needs.

How can I import grr results to ELK. **What about elastic search output plunge that you've mentioned earlier, is it ready?**

I'm thinking to use grr_output and export those csv files and then import them and parse into log stash. What do you advise?
https://kevinkirsche.com/2014/08/25/using-logstash-to-import-csv-files-into-elasticsearch/

thanks
George

**Comment by destijl** [comment]
Hey, @bwagner5 might be able to give you an update on where he is with this. Using CSV is probably the best option for now.

**Comment by micrictor** [comment]
I told a friend that I'd do this well over a year ago, and my parents always told me better late than never.

I already have a (mostly) working first pass at this, based mostly on the Splunk output plugin. For now, it will be directly indexing the documents via Elasticsearch instead of sending it into Logstash.

**Comment by max-vogler** [comment]
That's great news @micrictor! I'd be happy to review your PR and answer any questions.
