### ISSUE TITLE
Docker image not restartable since 3.1.0.2 - server.local.yaml moved

### ISSUE THREAD

**Issue by chlunde** [google/grr#401]
In`grrdocker/grr:v3.1.0.2`, the local configuration is no longer in `/etc/grr` like it was for 0.3.0-7.  It is now located in `/usr/share/grr-server/install_data/etc`.

`docker-entrypoint.sh` checks if the file has been generated in `/etc/grr`, so `grr_config_updater` is always executed, and restarting a container fails:

```
$ docker start -a b77f9e1a1e46
Traceback (most recent call last):
  File "/usr/share/grr-server/bin/grr_config_updater", line 11, in <module>
    sys.exit(ConfigUpdater())
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/lib/distro_entry.py", line 76, in ConfigUpdater
    flags.StartMain(config_updater.main)
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/lib/flags.py", line 121, in StartMain
Checking write access on config <YamlParser filename="/usr/share/grr-server/install_data/etc/grr-server.yaml">
...
-----END PRIVATE KEY-----
    main([sys.argv[0]])
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/tools/config_updater.py", line 863, in main
    InitializeNoPrompt(config_lib.CONFIG, token=token)
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/tools/config_updater.py", line 812, in InitializeNoPrompt
    GenerateKeys(config)
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/tools/config_updater.py", line 432, in GenerateKeys
    "override." % config.parser)
RuntimeError: Config <YamlParser filename="/usr/share/grr-server/install_data/etc/grr-server.yaml"> already has keys, use --overwrite_keys to override.
```

**Comment by scudette** [comment]
GRR Uses a main config file which contains factory set configuration (`grr-server.yaml`), and local config file `server.local.yaml` which contains local overrides. 

Generally the local overrides are expected to be stable between versions (they contain keys and installation specific things). OTOH the main config file is generally specific to a particular version of GRR. In this last release we decided to ship the `grr-server.yaml` file inside the virtual env because it applies to the specific version of GRR installed in that virtual env. However to make it easy to switch between different installations, the `server.local.yaml` file can be installed globally to the system so it can be easily used between different versions of GRR.

By default it is installed next to the grr-server.yaml (i.e. in the virtual env) but when GRR is installed to the system the location is switched to /etc/grr so it can be shared. You can see this in the grr-server.yaml file:

```
# When GRR is installed globally, we use the following global location for the
# configuration writeback. Otherwise the writeback is written into the
# virtualenv.
Global Install Context:
  Config.directory: /etc/grr/
```

If the docker file is trying to use the global location `/etc/grr/server.local.yaml`, then it needs to launch all the executables with the extra context - i.e. add this command line flag: --context "Global Install Context" so the configuration switches to using the global location for the writeback location.

**Comment by destijl** [comment]
I think this should just be a case of changing the check in the entrypoint.sh. I'll get it done later this week.

**Comment by destijl** [comment]
I've also created a backports branch:
https://github.com/google/grr/tree/server-3.1.0.2

and am building a docker tag "v3.1.0.2-latest" off that so you don't need to take the whole cryptography.io change to get this small fix.
