### ISSUE TITLE
XP clients in GRR 3.1.0.2

### ISSUE THREAD

**Issue by geneBursley** [google/grr#408]
Greetings,

I currently run 3.0.7.1 and began playing with the newest version.  On the old XP clients would not work unless we pointed the GRR.exe to the GRR.exe.yaml to get information. 

I thought I read that this issue was fixed for the newer versions, but I have been getting a crash before the client installs.  Is there a way to get them working, we have several legacy machines that cannot be upgraded at this time so we must be able to still check them if needed.

Here is a verbose from the debug installer:
![picture1](https://cloud.githubusercontent.com/assets/20309458/16618829/06c2c734-4351-11e6-83e1-750e8720d482.png)

**Comment by destijl** [comment]
Unfortunately we don't have the bandwidth to support XP. It's incredibly difficult and a complete waste of time for us. See here for our OS support statement:
https://github.com/google/grr-doc/blob/master/faq.adoc#what-operating-system-versions-does-the-client-support

Just getting a XP machine to reproduce your failure is a large amount of work since we have to find install media and build it from scratch, not to mention debugging, trying to make modern python install, finding ancient versions of visual studio to recompile in a way that might work, etc.

If 3.0.7.1 works, you're probably better off just leaving that there. An increasing amount of stuff won't work with the new server (notably memory analysis at the moment), but you should probably be able to do some basic file and registry retrieval for some time.
