### ISSUE TITLE
Duplicate files in sqlite datastore

### ISSUE THREAD

**Issue by keithtyler** [google/grr#418]
I noticed when you download a file (filefinder) the datastore creates two blob sqlite files. One is in the datastore root, the other is in the blob folder. The file in the root of the datastore only contains the table structure.

ls -lash /var/grr-datastore/3348930f51a63f6b7509160ffc94c431f987a7ead81209592a74eb2de08680ad.sqlite 
8.0K -rw-rw---- 1 root root 7.0K Jul 28 21:18 /var/grr-datastore/3348930f51a63f6b7509160ffc94c431f987a7ead81209592a74eb2de08680ad.sqlite

ls -lash /var/grr-datastore/blobs
168K -rw-rw---- 1 root root 167K Jul 28 21:18 3348930f51a63f6b7509160ffc94c431f987a7ead81209592a74eb2de08680ad.sqlite

**Comment by scudette** [comment]
This is a known bug which I have a fix for under review right now. The
issue is that the data store figures out the filename using two
different algorithms and sometimes it gets one filename and other
times it gets another filename which means that it will sometimes
appear to lose writes because some writes go to one file but it tries
to read them from the other file.

This is the code in question:
https://github.com/google/grr/blob/master/grr/lib/data_stores/common.py#L36

should be just:

def Components(subject):
  if not isinstance(subject, rdfvalue.RDFURN):
      subject = rdfvalue.RDFURN(subject)

  return subject.Split()

so it behaves consistently regardless of the type of inputs (which is
sometimes a string, and other times an RDFURN object).

Thanks
Michael.

**Comment by grrrrrrrrr** [comment]
Keith, does this work for you now?

**Comment by keithtyler** [comment]
yes, thank you!
