### ISSUE TITLE
change user password from WebUI

### ISSUE THREAD

**Issue by theshades** [google/grr#435]
Greetings,
Working on setting up a Beta like introduction into our environment, and the biggest complaint I have heard?
They cannot change their password from the WebUI.
If this could be added, that would be helpful.

Thanks!

**Comment by destijl** [comment]
You're going to bump up against these limitations if you rely on just the HTTP basic grr auth, because we don't expect you to be using it in production. See:

https://github.com/google/grr-doc/blob/master/faq.adoc#where-is-the-logout-button
https://github.com/google/grr-doc/blob/master/admin.adoc#authentication-to-the-admin-ui
