### ISSUE TITLE
GRR release cycle

### ISSUE THREAD

**Issue by SleuthKid** [google/grr#449]
I just realized that the version.ini file in the repo is ahead of the current .deb release.
As the install script for ubuntu is pretty small at the moment, there might be a possibility here to build automatic deb packages in a launchpad or bintray repo directly with the corresponding minor release numbers.

I really appreciate your very fast response times regarding bugs and general help for the community. I think it would be nice to get the small patches faster to the users in an automated way?!

**Comment by destijl** [comment]
There's two parts to this, server and client.

Client:
We build .deb, .pkg, and .exe templates on every commit with clean tests on travis and appveyor. You can download and repack those if you like. Be aware that you are trusting the travis and appveyor infrastructure.

Server:
The install script is small because it essentially just installs what is on pypi. So we'd actually have to automate releasing all of the packages onto pypi (core, server, test, and the client templates). See here for the previous server release tasks:

https://github.com/google/grr/issues/366

The difficult part in making a stable server (deb) release is that it is also a client release, so you need to build the client templates on 3 OSes, bring those templates back to one place, check they are actually going to work with the server, run the server, get end-to-end tests passing etc.

In contrast, tracking head following the pip install instructions is relatively easy if you're prepared to trade being up-to-date for less stability. This is essentially what we do internally.

We're not really happy with all of this build and release complexity, and we're discussing some ways to improve it.
