### ISSUE TITLE
Make the api_client a standalone package (and available in PyPi)

### ISSUE THREAD

**Issue by berggren** [google/grr#455]
It would be nice to be able to do:
$ pip install grr-api-client

In order to use the api_client code in third party integrations (e.g. [dfTimewolf](https://github.com/log2timeline/dftimewolf)) we need to depend on the whole GRR source which means a lot of unnecessary dependencies. Also, GRR is not in PyPi repos and is not easily installable. In short, it is a very heavy dependency to just get the api_client.

I propose we create a setup.py for this package and upload to PyPi. This way we can leverage the api_client library in third party tools.

**Comment by scudette** [comment]
GRR is in pypi and can easily be installed with pip. I think the problem is
that protobufs are shared with the main grr package so we need to maybe
extract into another package say grr-response-common.

Realistically it takes about 2 minutes to install the whole thing with pip
so the extra package, although it would be nice is probably not too urgent.

**Comment by mbushkov** [comment]
This is now done:
https://pypi.python.org/pypi/grr-api-client
