### ISSUE TITLE
Django debug mode turned on

### ISSUE THREAD

**Issue by itsacoderepo** [google/grr#474]
Hello,

the debug mode is turned on for django. I got a Traceback, including SUDO_UID, SUDO_GUID and SUDO_USER (besides other information). 

You can find the setting in the gui.py:
`
config_lib.DEFINE_bool("AdminUI.django_debug", True,
"Turn on to add django debugging")`

https://github.com/google/grr/blob/1dfc4d4cb37924db064d4f36245773bb74678068/grr/config/gui.py#L36

Here is a statement from the django documentation (https://docs.djangoproject.com/en/1.10/ref/settings/#std:setting-DEBUG):
```
DEBUG
Default: False
A boolean that turns on/off debug mode.
Never deploy a site into production with DEBUG turned on.
```

**Comment by grrrrrrrrr** [comment]
Hey,

Thanks for reporting this. I don't think this is a huge security risk since the ui should be protected anyways but having the default set to debug is definitely not a great idea, I agree :/

The good news is that we actually got rid of Django entirely in a recent commit (Yay!) so this option doesn't do anything anymore at this point and will soon be removed. I don't think there is anything for us to do at this point since this is kind of obsolete already.

If you do not run from head, please add

AdminUI.django_debug: False

to your server config which prevents this problem.

**Comment by grrrrrrrrr** [comment]
GRR no longer uses Django (\o/) so this is no longer an issue.
