### ISSUE TITLE
Grr_console AnaylzeClientMemory "Request=Request" - Syntax??

### ISSUE THREAD

**Issue by kalle44** [google/grr#511]
Hi, 

hopefully someone can help me.

I want to start a "AnalyzeClientMemory" flow via grr_console.
The rekall-plugin should be "yarascan". The plugin argument "yara_expression".

So, basically I want to search the clients memory with an yara-signature.

Therefor the Flow-Spec is:

flow.GRRFlow.StartFlow(client_id=client_id, flow_name="AnalyzeClientMemory", request=request, debug_logging=debug_logging, max_file_size_download=max_file_size_download, component_version=component_version)

"request=request" is used to say, which rekall-plugin to use (I think so)

My issue is, I can't find out the syntax for "request=request". What is the syntax for using a rekall-plugin here like "yarascan" oder "pslist"?

Greetings from Germany,
John

**Comment by mbushkov** [comment]
Hi John! Quick question - what exactly are you trying to achieve by using grr_console? Are you scripting some logic or doing some batch processing?

When dealing with any action that's accessible from GRR Admin UI (and starting a flow is one of them), the best way to script is by using GRR API. The difference in using grr_console and GRR API is that grr_console gives you access to GRR internals and requires a lot of intrinsic knowledge of GRR, whereas GRR API is a well-defined interface that's unlikely to change.

Latest version of GRR displays a hint for every flow with a CURL command required to start a similar flow on the same client. See this screenshot for details:
<img width="980" alt="yarascan_example" src="https://user-images.githubusercontent.com/904981/27006544-caee579a-4e36-11e7-8941-815ab2483ce8.png">

Instead of using the raw HTTP API you can use the GRR API library and grr_api_shell (https://github.com/google/grr/tree/master/api_client/python#grr-api-client-library). grr_api_shell is an IPython-based shell, but whereas grr_console gives you direct access to GRR internals, grr_api_shell is a wrapper around a public GRR API.

Here's an example of how to run the flow you need using grr_api_shell. To run grr_api_shell:

```
# Inside virtualenv:
pip install grr_api_shell
grr_api_shell --basic_auth_username admin --basic_auth_password demo http://localhost:8000
```

Inside grr_api_shell:
```
c = grrapi.Client("C.05c701e9f2b97a20")
args = grrapi.types.CreateFlowArgs("AnalyzeClientMemory")
print type(args) # grr.client.components.rekall_support.rekall_pb2.AnalyzeClientMemoryArgs
plugin = args.request.plugins.add()
plugin.plugin = "yarascan"
data = plugin.args.dat.add()
data.k.string = "yara_expression"
data.v.string = "blah"
flow = c.CreateFlow("AnalyzeClientMemory", args)
print "Flow started: %s" % flow.flow_id
```

**Comment by kalle44** [comment]
Hi mbushkov,

to answer your first question - what i'm trying to do is write a python-script to choose a yara-rule from a repository and handle over the signature to grr to scan the clients memory. Basically, some kind of yarascan-automation.

So thank you for your input. I thougt using the grr_console is the way to do it, but the grr_api_shell is obviously  the better idea. :)

_"Latest version of GRR displays a hint for every flow with a CURL command required to start a similar flow on the same client. See this screenshot for details:"_
Ok, I installed my grr-version a week ago by using the install_script, but I don't have the option to see the CURL command. See this screenshot:

![gr_screenshot](https://user-images.githubusercontent.com/29337312/27009378-7aa07b00-4e8c-11e7-8f08-8bff7cc30ac7.PNG)

Maybe you have a different grr-version?

**Comment by mbushkov** [comment]
Yes, most likely you've installed the release version. You'll need the HEAD version in order to use the API. The API is the preferred way of automating GRR, because it should be easier to do so via the API and because it was designed to be stable and backwards-compatible. 

To install GRR from HEAD: https://github.com/google/grr-doc/blob/master/installfrompip.adoc#installing-grr-server-for-dev-ie-tracking-head

You'll likely need to install a protobuf compiler in order for GRR to build, see https://github.com/google/grr/blob/master/travis/install_protobuf.sh - make sure to export `PROTOC` environment variable pointing to the protoc binary.

If you use Docker, then using `grrdocker/grr:latest` version should do the trick (see https://github.com/google/grr-doc/blob/master/docker.adoc).

Please tell me if you have troubles with installing GRR from HEAD.

**Comment by kalle44** [comment]
Hi mbushkov,

I installed GRR from HEAD following the instructions.
After the installation finished, I run the _grr_config updater initialize_ command to set the config.

I can't reach the UI when I point my browser to the URL. 
It seems the Server isn't running.

Do I have to start some grr-services?

**Comment by mbushkov** [comment]
Yes, sorry, this part totally slipped away. 

Normally we recommend installing release GRR version first and then overriding the GRR_PREFIX environment variable to point to the HEAD version (see bottom part of https://github.com/google/grr-doc/blob/master/installfrompip.adoc for details). This way services files from Debian package are still used but point to GRR's version from HEAD. Unfortunately we've done a few backwards-incompatible renamings which make this approach impossible.

The simple solution is to just run all GRR components in the command line:
```
source /usr/share/grr-server/bin/activate
grr_server --component admin_ui --disallow_missing_config_definitions --verbose &
grr_server --component frontend --disallow_missing_config_definitions --verbose &
grr_server --component worker --disallow_missing_config_definitions --verbose &
```

An alternative (albeit more sophisticated) solution is to build GRR Debian package using Docker as specified here https://github.com/google/grr-doc/blob/master/admin.adoc#building-the-server-debian-package and then install it. This package will include necessary configuration files to run all server components on system startup.

Hopefully we'll make a new GRR server release rather soon so as to make building from HEAD unnecessary.
