### ISSUE TITLE
Is calling "prelink -u" really needed when repacking client RPM packages?

### ISSUE THREAD

**Issue by hillu** [google/grr#521]
Hi,

In https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=863295, we got the request to remove the prelink dependency of the grr-server package. As far as I can tell from the commit history and from issue #367, having prelinked binaries used to cause problems, so the prelink sections are removed by calling `prelink -u` when repacking the RPMs (grr/lib/build.py, `CentosClientRepacker`). I checked the current templates and did not find any prelinked binaries, so I wonder if this step is still useful.

Cheers,
-Hilko

**Comment by mbushkov** [comment]
Hi Hilko! I took a brief look: it seems that we can either remove the prelink dependency completely or, alternatively, move this dependency to the templates building step (instead of templates repacking step) - this will allow to remove the prelink dependency from the grr-server package.
We need to do a few more checks, I'll keep you updated.
