### ISSUE TITLE
Artifacts update with makefile.py does not work

### ISSUE THREAD

**Issue by n3x77** [google/grr#525]
Dear all,

It seems that the https://github.com/ForensicArtifacts/artifact Repo changed the structure of the repo from definitions to data. After that change the makefile.py script of GRR Version 3.1.0.2 does not work anmyore because the script in /usr/share/grr-server/lib/python2.7/site-packages/grr/artifacts inclused the following 
```python 
def main():
  data = urllib2.urlopen(
      "https://github.com/ForensicArtifacts/artifacts/archive/master.zip").read(
      )
...
  for name in zip_obj.namelist():
    if fnmatch.fnmatch(name, "*/definitions/*.yaml"):
...
```

This needs to be changed to:
```python
for name in zip_obj.namelist():
    if fnmatch.fnmatch(name, "*/data/*.yaml"):
```
Otherwise the artifact store is broken. 

Cheers,
Sven

**Comment by grrrrrrrrr** [comment]
Hey Sven,

This is true and already changed: https://github.com/google/grr/blob/master/grr/artifacts/makefile.py

I agree that this is not great though since it breaks the old server deb. We should probably pin the artifacts to a release when we build a server deb instead.

I'll consider this as fixed already but thanks for the (detailed!) report anyways.

Cheers,
-Andy
