### ISSUE TITLE
Fail to load component for MemoryCollector flow

### ISSUE THREAD

**Issue by jawilson0502** [google/grr#528]
I've been attempting to run "MemoryCollector", and I receive a 404, similar as to what happens in https://groups.google.com/forum/#!topic/grr-users/5RQxLaZjWYw

This seem to stem from the issue of the rekall component defaulting to "1.6.0", but only having "0.4" available. When running "AnalyzeClientMemory", if I click "Advanced", I can choose the component version, which allows the component to run. With "MemoryCollector", I cannot. 

I see two obvious solutions for this - First default the component version to "0.4" instead of "1.6.0", or second create an advanced option within "MemoryCollector" that allows me to define the component version I want to use.

**Comment by grrrrrrrrr** [comment]
Hey,

I agree, we should have a component version selection for the memory collector. We are currently removing component support entirely because of the constant small issues they cause - the next client generation will have Rekall built in and it will hopefully be more reliable. This feature request is therefore rather low priority I'm afraid but I'll see what we can do.

The optimal solution for you would probably be to use component v1.6.0. Is there any reason you prefer the old one?

Cheers,
-Andy

**Comment by mbushkov** [comment]
@grrrrrrrrr -  here's a bit of context: https://github.com/google/grr/issues/508#issuecomment-308049698

Basically, there seems to be an issue with uploading newer versions of components when previous versions already exist. In this case the new versions don't work. When one updates GRR server to the version from HEAD, then default Rekall component version is set to 1.6.0, but uploading 1.6.0 components doesn't work due to this issue. So one has to manually override components version to be 0.4.

@jawilson0502 , as Andy said - we're deprecating components and in the next release the clients will be monolithic again - i.e. the clients will include Rekall right after the build. In fact, our current nightly-built clients are already built this way.

**Comment by jawilson0502** [comment]
Sounds great! I'm excited to see the new changes.

**Comment by grrrrrrrrr** [comment]
New clients with Rekall built in are released, closing this issue.
