### ISSUE TITLE
API: Inconsistent use of `AnyValue`, `bytes` for generic message fields

### ISSUE THREAD

**Issue by hillu** [google/grr#530]
Among the API messages defined in the *.proto files of GRR 3.1.0.2, generic fields are usually defined using `AnyValue` messages which contain type information and a `bytes` buffer. This seems to be the case for all messages that travel from the GRR server to the client as part of `Api*Response` messages, but some message types use a simple `bytes` buffer with no space for type information.

For instance, the 

- `CreateFlow` (POST `/api/clients/<client_id>/flows`) expects `ApiCreateFlowArgs` -> `ApiFlow`: `args` is an `AnyValue`.

but:

- `CreateHunt` (POST `/api/hunts`) expects `ApiCreateHuntArgs` -> `GenericHuntArgs`: `flow_args` is a `bytes`

Shouldn't those be changed to `AnyValue`?

Other examples (not sure how they are used):
- `CreateCronJobFlowArgs`: `flow_args` is a `bytes`
- `FlowRequest` `args` is a `bytes`.
- `ClientActionArgs`: `action_args` is a `bytes`
- `ConsoleDebugFlowArgs`: `flow_args` is a `bytes`.

**Comment by mbushkov** [comment]
Hi Hilko! Thanks for asking - this is an interesting question.

Historically, we used to store dynamic data (i.e. arbitrary protobufs) as bytes. We were annotating corresponding protobuf fields with sem_type {dynamic_type = "..." } annotation. "dynamic_type" was pointing to a Python function that had to be called to find out the type of the data stored in the field.

As soon as we started working on the API, limitations of such approach became apparent. It was impossible to read such protobufs not in Python, and even when using Python one had to depend on GRR source code to do the parsing. By that time a google.protobuf.Any (https://github.com/google/protobuf/blob/master/src/google/protobuf/any.proto#L112) was introduced, so in the API layer instead of storing dynamic fields in bytes, we started to store them as Any messages (in the beginning we were using AnyValue definition, which was a copy of google.protobuf.Any).

As a result, all the API-related data structures have dynamic fields defined with google.protobuf.Any. But whenever you have to deal with the older non-API-related protobufs, you hit the issue of dynamic fields being stored in bytes instead of google.protobuf.Any/AnyValue. 

These older data structures can be updated to use google.protobuf.Any, but this change would be backwards-incompatible and has to be done with care. I'll look into deprecating the "bytes" approach and using google.protobuf.Any for everything.

Please keep in mind that we changed ApiCreateHuntArgs to be more user-friendly. Compare older release version (https://github.com/google/grr/blob/server-3.1.0.2/grr/proto/api.proto#L789) with a newer HEAD one (https://github.com/google/grr/blob/672eaf4c4b4fbd8d53fc33b98b243efd6976a73c/grr/proto/api/hunt.proto#L510). I also plan to do a similar simplification for the cron jobs.

**Comment by hillu** [comment]
Mikhail,

it's good to see that improvements are being made to the messages, but I am still stuck with 3.1.0.2. (plus the various bugfix patches I made). Is a stable release planned for the near future?

**Comment by mbushkov** [comment]
Hi Hilko,
Yes, the stable release is definitely planned this quarter.

**Comment by grrrrrrrrr** [comment]
Is there anything left to do here? Seems like we could close this issue now that the stable release is out?

**Comment by hillu** [comment]
@grrrrrrrrr the structs have not been changed yet...

**Comment by mbushkov** [comment]
Hi Hilko, sorry, I think I misunderstood https://github.com/google/grr/pull/536#issuecomment-326730353. I had the impression that you're working on a PR that fixes the issue. If that's not the case, I'm happy to implement the changes and cut a new release when they're done and working.

**Comment by hillu** [comment]
@mbushkov I would like to try to get something done by next weekend (say, Oct. 15).

**Comment by mbushkov** [comment]
@hillu - quick question. ApiCreateHuntArgs were fixed to use google.protobuf.Any some time ago (https://github.com/google/grr/blob/85d75df52d056daf77a6b465e2ef09cfae29a549/grr/proto/api/hunt.proto#L523) and new ApiCreateHuntArgs version is included in the latest release.

Are there other data structures where having "bytes" instead of "google.protobuf.Any" blocks you?

**Comment by grrrrrrrrr** [comment]
I'll close this, if there are more examples for bytes vs. any, please reopen.
