### ISSUE TITLE
Question - can it monitor on a daily basis and give reports?

### ISSUE THREAD

**Issue by Davis8988** [google/grr#540]
I am looking for a software to monitor all the details of computers in my lab.

Details that are important to me: 
Computer - computer name  , Cores , Hyper threading(YES/NO)  , Total RAM , Disk Usage , Disk Free Space.
Network - Switch name  ,  Adapter (nick)Name , Port Number ,  MAC address , IP address , Gateway , VLAN , Link Speed.

I have a lab with about 60 computers and these details tend to change frequently in the lab. I want the software to alert me on a daily report or so when something was changed. Since it can cause trouble if something changed and It will take me a long time to figure out what. 
I need a software that can tell me instantly if my lab is not functioning because one of these details above was changed. 

Can your software do that?  

Thank you,
David

**Comment by grrrrrrrrr** [comment]
Hey David,

GRR collects most of the information you mention and it also wouldn't be hard to add the data it's currently missing. The way GRR works is that there is full history of the data collected so generating the reports you'd like to have would be feasible too.

Having said that, what you really need is some sort of fleet managing software, not a forensics tool. You can make GRR provide the information you need but it will always be a bit hackish since it's just not GRR's main use case.

Cheers,
-Andy

(closing this issue since it's not really an issue)
