### ISSUE TITLE
client --plugins option does not do anything

### ISSUE THREAD

**Issue by scudette** [google/grr#588]
This feature seemed to have been removed. It makes it difficult to make slight modification to the client (e.g. by just including new python files to the package and changing the config to point at them). Please consider bringing it back.

In any case the flag does not do anything now so maybe it should be removed.

**Comment by grrrrrrrrr** [comment]
We decided two years back that maintaining the client plugin system is too much work for what it buys us. This is the first time since then that somebody complains so the decision was definitely not completely wrong. I know that sometimes it's nice to have this option but given how easy it is to rebuild clients nowadays, adding a debug option that doesn't make it to production is probably an acceptable alternative.

I'll remove the flag in the next push.

**Comment by grrrrrrrrr** [comment]
Removed in https://github.com/google/grr/commit/a384b4bd8d4c156119c5b258e20b7fd5d555945a
