### ISSUE TITLE
Key kept in clear-text in Registry

### ISSUE THREAD

**Issue by cwilsonwoof** [google/grr#591]
Hi Team,

I noticed the GRR agent key is kept in clear-text in the registry making it very easy to find and extract using standard key scraping techniques. Could we get a layer of obfuscation?

**Comment by MariasStory** [comment]
@cwilsonwoof has a point there. Just defend from stupid automation and make them work to get the key. If additional deobfuscation is required, it might be not worse to play with it.
BZW: The same stands for memory obfuscation and protection.

**Comment by scudette** [comment]
You need to consider what happens if the key is compromised. If order to get the key from the registry the attacker has to be admin (due to reg permissions). Once they get the key they get the ability to impersonate *as that one client*. So they can technically rebuild another machine and communicate that other machine with the server and pretend they were the first machine.

This obviously does not really give them much since the attacker must already be admin on the first machine and so they can just make GRR do whatever on the first machine. I am not sure this really increases the risk any.

**Comment by grrrrrrrrr** [comment]
Michael is totally right here, there is just no additional gain by stealing the key for an attacker that is already root on the target machine. Also note that deobfuscation can be easily automated as well so the point about thwarting automation doesn't really hold either.

The same is true for most obfuscation techniques btw, for example the memory obfuscation you mentioned. An attacker has to figure this out your algorithm only a single time which shouldn't be too hard but you have to live with the additional complexity. It's really not a good trade-off.

I'll close this issue here, I don't think this is something we will want to change.
