### ISSUE TITLE
How to rebuild GRR.exe or GRRservice.exe?

### ISSUE THREAD

**Issue by w44p** [google/grr#597]
How to rebuild GRR.exe or GRRservice.exe?
My purpose is to run grr client without installtion. But I find grr client must run  GRRservice.exe and GRRservice.exe must use --service_key "Software\GRR" to install a service under Windows. 
How to rebuild *.exe so I can run grr client without installtion under Windows ?
And how to do in Linux?
Thanks!

**Comment by grrrrrrrrr** [comment]
If you want to run the client without installation, you don't need to build the service binary or the template - you can use the client entry point and run the client from the command line.

If you actually need to rebuild templates and service binary, we have some instructions about setting up dev environments for the different platforms, have a look at https://grr-doc.readthedocs.io/en/latest/maintaining-and-tuning/building-custom-client-templates.html

**Comment by grrrrrrrrr** [comment]
What's your reasoning behind this request? You will always have to install some software on the machine to make GRR run.

If you use the prebuilt binaries, the installer will bring all dependencies (including the Python support you mentioned for example) which makes is very easy and low impact to run GRR. If you want to run GRR directly from source, you will still need to install all the dependencies which will also alter the client machine - probably to a bigger extend than using the GRR installer.

**Comment by scudette** [comment]
There are some use cases where it is not required to install the grr binary as a service because the binary can get persistence another way. For example on GCP it is possible to set a "startup script" in the project metadata which will ensure that the binary can run every time the machine is started (even if a new machine is provisioned). Because of this you dont need to install it as a service - just download it and run it on boot time.

The GRR client is shipped as a binary with a bunch of dlls and other support files. It does not actually need to be installed - you can just arrange to have the grr client directory unpacked somewhere (e.g. by unzipping it) and then just run the client normally - grrd.exe --config .... It should work if you just zip up the directory from a windows box (normally c:\windows\system32\grr\grr_version\**) with the proper client installed and then you can unpack it where ever you want.

The default config uses the registry to store configuration but you can just override that in the grrd.exe.yaml file to point at a file if you dont want to leave behind registry artifacts. Be aware that the client will need to create its own keys and so it has to write it somewhere (maybe in a tmp location?). If your local config writeback is not persistent then the client will keep changing its client id all the time.

This approach should work also with other operating systems. On GCP you sometimes come across machines which have chrome os installed and then the regular installers (dpk, rpm) wont work. A simple tgz file should work better (just remember to unzip it to a partition which has execute permission :-).

**Comment by w44p** [comment]
Thanks to grrrrrrrrr and scudette.
 I can use "grrd --config=XXXXX" in Linux to run the client directly.
But when I'm under Windows, I don't want the client installer to write to the registry. So I modified the GRR.exe.yaml configuration file and let it write to a file. After installing "GRR.exe --install --config GRR.exe.yaml", the installation fails.
ERROR:2018-06-19 14:19:21,546 installer:69] Installation failed: Command '[u'E:\\000temp\\GRR\\3.2.2.0\\GRRservice.exe', '--service_key', u'Software\\GRR', 'install']' returned non-zero exit status -1
The execution of GRRservice.exe --service_key "Software\GRR" install failed because he would look for 'Software\\GRR' in the registry and I did not write it to the registry. If 'Software\\GRR' is replaced with my specific file, it will prompt: Unable to open service key, the system cannot find the specified file.
How should this place be handled?

**Comment by scudette** [comment]
When you run --install you tell grr to install itself which it does by writing the registry and installing the service and various other things. 

As I understand it you dont actually want to install it right? Maybe I dont quite understand what you are trying to achieve. How are you proposing to get persistence?

**Comment by w44p** [comment]
可能我之前没有表述清楚。我确实不想通过安装来运行客户端。在linux下，我已经找到了“grrd --config=XXXX”来直接运行客户端。但是在windows下，我没有找到命令来直接运行客户端。我也尝试过"GRR.exe --config GRR.exe.yaml"，但是命令执行失败了。
报错如下：其中'E:\000temp\logfiles\writeback.txt'是我指定的Config.writeback
DEBUG:2018-06-19 14:46:35,443 comms:1450] sending enrollment request
Traceback (most recent call last):
  File "site-packages\grr_response_client\client.py", line 61, in <module>
  File "site-packages\grr\lib\flags.py", line 122, in StartMain
  File "site-packages\grr_response_client\client.py", line 57, in main
  File "site-packages\grr_response_client\comms.py", line 1395, in Run
  File "site-packages\grr_response_client\comms.py", line 859, in SendNannyMessage
  File "site-packages\grr_response_client\client_utils_windows.py", line 277, in GetNannyMessage
  File "site-packages\grr_response_client\client_utils_windows.py", line 246, in _GetServiceKey
AttributeError: 'module' object has no attribute 'E:\000temp\logfiles\writeback.txt'
Failed to execute script client
What commands need to be executed under windows to run directly?
@scudette

**Comment by scudette** [comment]
Ah I see. In theory the client can support its config not being in the registry but I think you have discovered a bug/misfeature. It seems that the windows client is hard coded to use a nanny service through the registry.

So I guess currently it is not possible to run the windows client not through the registry. Perhaps this is a feature request?

**Comment by w44p** [comment]
I tried using different configurations. In the case where the value of Client.config_hive and Client.config_key is empty, configure Config.writeback to my local file. This will use the command to start the client successfully. If the values of Client.config_hive and Client.config_key are also configured to my local file path, the client cannot be started.
Because I expect to place the client on some machine being checked without destroying the environment of the machine, I have this idea of running without installation.
Thank you for your help.
