### ISSUE TITLE
Installing sits at 99% Ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by McFarkey** [google/grr#626]
I am installing grr-server_3.2.3-2_amd64.deb on Ubuntu 16.04 LTS and it just sits at 99% for 2 hours now.
Any ideas/comments/thoughts?

Thanks to all.

**Comment by mbushkov** [comment]
Are you choosing MySQL as your datastore type?

There is a known issue (fixed in HEAD) where the installation would block indefinitely if GRR is unable to connect to MySQL (when setting up a MySQL datastore).

Can you try installing GRR from a HEAD deb and check if it also gets stuck or not? (see https://grr-doc.readthedocs.io/en/latest/installing-grr-server/from-head-deb.html)

**Comment by demonchild2112** [comment]
I'm closing this. Feel free to re-open if the issue continues in the latest GRR release.
