### ISSUE TITLE
无法在windows上安装grr客户端

### ISSUE THREAD

**Issue by Linoonphan** [google/grr#632]
在windows上安装好grr客户端时，
net use \\192.168.0.145\IPC$ /USER:root *
请键入 \\192.168.0.145\IPC$ 的密码:
发生系统错误 53。
找不到网络路径。

**Comment by grrrrrrrrr** [comment]
Sorry we never responded to this. I'll close the issue due to language difficulties.

If you still need help, please reopen and we'll try to make this work somehow. If you can, please add a description in English or any of the many other languages we speak in the team - you will get better answers...
