### ISSUE TITLE
Moving to MySQL for an existing GRR deployment

### ISSUE THREAD

**Issue by coonsmatthew** [google/grr#634]
Hello all, 

I'm interested in moving to MySQL for our existing GRR deployment that is currently using SQLite. Reading the documentation makes it clear that there is no data migration process, but can I move to the new datastore without having to re-deploy/configure all of my clients and configure my apache webserver? 

I wasn't sure if I complete the upgrade process and select MySQL from that? Or would that mean that my clients wouldn't be able to log into the server again and I would need to start from scratch again? 

Thank you.

**Comment by pidydx** [comment]
As long as the keys all remain the same you shouldn't have any problem redeploying the datastore.  I am still working through the process of trying to release our updated MySQL datastore that solves a lot of the scalability problems, but I have repeatedly blown out the entire thing and let everything reenroll as I changed the schema and such.

One thing to be aware of is that the current version of GRR doesn't have a way to deal with a surge in enrollment.   So if you have a lot of clients they will all try to enroll the next time they check in which leads to Interrogate being run on each host twice and can cause a lot of load until everything gets enrolled.  I have another update I am trying to release that alters how the enrollment process works so that if you have a large fleet you can safely reset the datastore and it will control the enrollment rate better.

**Comment by coonsmatthew** [comment]
So, question #2. I'm dealing with around 1000 clients. Right now I've got around 100 clients enrolled with SQLite, but I will be enrolling around 900 more, for a total of 1000. Is it safe to stay with SQLite for now, or will it fall over with that number of clients? 

Thanks.

**Comment by coonsmatthew** [comment]
And, thank you for the help!!

**Comment by coonsmatthew** [comment]
I actually just updated the datastore to MySQL, and it worked like a charm! So kudos to your team on the upgradability. My clients are checking in and getting added to the datastore!
