### ISSUE TITLE
API Client: Python 3 Error for Next/Iterator

### ISSUE THREAD

**Issue by weslambert** [google/grr#679]
Hello,

I'm getting the following error using the API client with Python 3 when trying to collect client IDs:

`AttributeError: 'generator' object has no attribute 'next'`

I've traced the issue to:

https://github.com/google/grr/blob/master/api_client/python/grr_api_client/context.py#L54

If I change that line to:

`first_page = pages.__next__()`  

(see: http://diveinto.org/python3/porting-code-to-python-3-with-2to3.html#next; looks like item number 4 may be backwards compatible)

...it works fine, but I'm not sure that provides backwards compatibility for Python 2.

I could of course check for the version and modify it as needed, however, I figured I'd bring this up to you guys to see if you had an appropriate fix or any better ideas before I attempted to submit a PR.

Thanks,
Wes

**Comment by weslambert** [comment]
Hi, I was wondering if there was any movement on this?  I'd like to include use of the GRR API client with an API I am utilizing, but because the API is written Python 3, I'm not able to do so.  Any feedback is appreciated.

Thanks!
Wes

**Comment by mbushkov** [comment]
Hi Wes! Thanks for bringing this up. The bug is fixed in HEAD (see https://github.com/google/grr/blob/master/api_client/python/grr_api_client/context.py#L54), but we didn't release new PIP packages, so when you were installing grr-api-client from PIP, it was still buggy on Python 3.

I've just released the grr-api-client PIP package (version 3.2.4.9) from the latest GRR build. It shouldn't have the generator bug and should work fine on both Python 3 and Python 2.

**Comment by weslambert** [comment]
Hi @mbushkov !  Thanks for the quick response!  I'll give it a go, and report back.

Thanks!
Wes

**Comment by weslambert** [comment]
Confirmed this issue has been resolved.  Thanks, @mbushkov !
