### ISSUE TITLE
best practive to retrieve dll file hash values

### ISSUE THREAD

**Issue by 4688-is-great** [google/grr#683]
First of all, big thanks for creating such a powerful IR tool!  One of our goals is to compare windows dll file hash values across 100+ machines.  This is for doing IR at various client sites, so GRR would be installed and analysts who prefer to use SQL will want the hash details as soon as reasonably possible.  The idea is to define what "normal" looks like in the VFS and registry haystack so that we can pinpoint the outliers / needles.

- When navigating the VFS in the admin GUI, if we click on the recursive collection button, is that similar to doing a STAT (action) file finder-flow?   
- Is the HASH action file-finder flow the best way to get the HASH values into the mysql subjects table?  

We want to avoid the time it would take to retrieve the entire file over the network and only want to get the files, filepaths, and hashes.

**Comment by 4688-is-great** [comment]
I meant to write we "only want to get the FILENAMES, filepaths, and hashes."

**Comment by grrrrrrrrr** [comment]
Hey,

Using the file finder with the HASH action will give you exactly what you want - file hashes but no content.

Note that we generally discourage overusing hashes (see http://grr-response.blogspot.com/2015/05/hashing-maslows-hammer-of-forensics.html ) but your specific use case seems rather reasonable. Still, I'd keep in mind that this puts quite a bit of load on your client machines.

If you want to avoid using the UI ("use SQL"), I'd suggest you run that file finder flow using the API and retrieve the results as a CSV. You could automate that whole workflow easily if it's something you want to do often...

Cheers,
-Andy

**Comment by mbushkov** [comment]
+1 to Andy's suggestion.

One more thing: If you have to collect hashes for the same set of files on a set of clients, I'd suggest using [hunts](https://grr-doc.readthedocs.io/en/latest/investigating-with-grr/hunts/index.html) rather than running individual flows (you can run a FileFinder hunt with HASH action). Then you can download all hunt results as CSV or, even better, as an SQLite SQL file for further analysis.

As Andy pointed out, both hunts and flows scheduling (and results downloading) can be automated with [GRR API client library](https://github.com/google/grr/tree/master/api_client/python).

**Comment by Karneades** [comment]
@4688-is-great Just a small idea for your question: Unless you need these file hashs for other purposes too, you could instead of checking windows dll file hashs (which sometimes differ a lot between versions and between clients), check the file signatures (file signature or authenticode signature) and only report if the signature is invalid. If you run that regularly for baselining, you could implement a dedicated flow for that.
