### ISSUE TITLE
Failed to import NSRL file

### ISSUE THREAD

**Issue by eulmatxlm** [google/grr#689]
Hello,

Context:
brand new grr server installed from deb (ubuntu 16.04, grr 3.2.4-6).

We are trying to import the NSRL file following this documentation:
https://grr-doc.readthedocs.io/en/latest/investigating-with-grr/importing-nsrl.html

We downloaded the rds_modernm.zip file (f842d8a3d79e0cec5a9cfccc55953f41), uncompressed it, and issue the following command:
 /usr/share/grr-server/bin/python /usr/share/grr-server//lib/python2.7/site-packages/grr_response_server/bin/import_nsrl_hashes.py --config /etc/grr/server.local.yaml --filename  NSRLFile.txt

Unfortunately, the process fails after a while with this error: 

Traceback (most recent call last):
  File "/usr/share/grr-server//lib/python2.7/site-packages/grr_response_server/bin/import_nsrl_hashes.py", line 106, in <module>
    flags.StartMain(main)
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_core/lib/flags.py", line 147, in StartMain
    main(sys.argv)
  File "/usr/share/grr-server//lib/python2.7/site-packages/grr_response_server/bin/import_nsrl_hashes.py", line 100, in main
    imported = ImportFile(store, filename, flags.FLAGS.start)
  File "/usr/share/grr-server//lib/python2.7/site-packages/grr_response_server/bin/import_nsrl_hashes.py", line 42, in ImportFile
    reader = csv.Reader(fp.read())
  File "/usr/share/grr-server/lib/python2.7/codecs.py", line 314, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xe7 in position 4042147: invalid continuation byte

Looking at the specified position in the file, we get indeed a "ç" character (hexdump following)

...
00000050  30 37 30 33 45 42 32 22  2c 22 66 72 61 6e e7 61  |0703EB2","fran.a|
00000060  69 73 2e 6c 61 6e 67 75  61 67 65 22 2c 32 38 31  |is.language",281|
...

Is there something wrong with the command we used or maybe the configuration of the ubuntu (language was set at install time to en_US.UTF-8)

Thanks!

**Comment by mbushkov** [comment]
Hi! This seems to be unicode bug.

The thing, though, is that NSRL import is something that's about to be deprecated. How did you plan to use NSRL hashes? We asked this question on the mailing list some time ago and got the impression that NSRL hashes import is not an actually used feature https://groups.google.com/d/msg/grr-users/C45ex3y0TDg/60zoJu17CQAJ

IIRC, importing NSRL hashes was initially conceived as an optimisation technique - so that the files with given hashes are not collected from the clients (because we know which files stand behind the hashes anyway). However, unless you drastically need to optimise your GRR network traffic, there seems to be not much use for this feature.

**Comment by eulmatxlm** [comment]
Hi,
We actually are in the process of testing various products such as grr, so for now it's more verifying the announced capabilities and testing them.
The idea of having a known list of "safe" (known) hashes directly available from grr sounded nice, as for example it could have been used to focus our efforts on all the other "unknown".
However, as the feature is going to be deprecated, will proceed another way, thanks.

**Comment by grrrrrrrrr** [comment]
We removed the NSRL feature since it takes too much time to maintain compared to what it gets us so this issue is obsolete.
