### ISSUE TITLE
Preferred mechanism for client upgrades in 3.3.0.0

### ISSUE THREAD

**Issue by atkinsj** [google/grr#711]
I notice that the administrative flow for "Client Upgrade" was removed in 3.3.0.0. Is the preferred client upgrade mechanism now the same way you get the clients down initially (i.e., organisational config management ala puppet/sccm/pdq/JAMF/etc?).

If that's the case, is there any documentation / things I should know before doing so? Can you just run the 3.3.0.0 client executable on a host that already had 3.2.4.6 and it will just work or do you need to clean up the old versions first?

**Comment by mbushkov** [comment]
Hey! We still do have the "UpdateClient" flow. It should be available in the "Administrative" flows category (https://github.com/google/grr/blob/3fd32ca19b3984fcfd8fec10637e0dd06a582410/grr/server/grr_response_server/flows/general/administrative.py#L636). It's an "ADVANCED" flow, so make sure you have "ADVANCED" mode turned on, otherwise the flow will be hidden (you can click on the settings button in the top right corner to change the UI mode).

Can you please check if you see the UpdateClient flow in your UI?

Some more notes about client updates:

- To update a client you simply need to run a repacked 3.3.0.0 installer, it will disable the old client and correctly install on top of it. You don't have to do anything manually.
- The UpdateClient mechanism should still work and we have no plans of removing it.
- However, if you have an option to configure Puppet or any other deployment management tool to deploy GRR clients (and other software), that's certainly preferable to the ad-hoc UpdateClient approach. UpdateClient-based process is simplistic, it doesn't have any kind of a rollback procedure and provides only a limited insight into whether the update process was successful or not. If something goes wrong you effectively lose access to the client and have to use a third-party tool to reinstall it. By using Puppet or the likes for fleet software management you're effectively using the tool which was specifically designed for managing software and you're protecting yourself from potential issues: i.e. if GRR stops working, you have Puppet to redeploy it (and vice versa: GRR can be used in emergency cases to fix issues with Puppet).

**Comment by atkinsj** [comment]
Hah, I also switched to AFF4 to REL_DB and didn't consider that it'd untick the `advanced` setting on my user, because my user came from SSO and I didn't have to recreate it. ;)

I now see it. Thanks for the detailed explanation as for the update options. We do deploy via config management so upgrading via the same tools should be pretty trivial, I just like using UpdateClient first before I push it to our IT team.

Thanks again!

**Comment by atkinsj** [comment]
Hm, whops, one quick question.. UpdateClient doco still shows an aff4: path, has this changed under REL_DB? What path should I be providing?

**Comment by mbushkov** [comment]
Yeah, sorry - this is still an artifact from the pre-REL_DB times.

The path should be: `aff4:/config/executables/<binary path>` where `<binary path>` is the path you see in the "Binaries" page of the UI.

We'll fix this in the next release when AFF4 will be fully deprecated and removed from the codebase.

**Comment by atkinsj** [comment]
Great, figured but thought I'd double check. Thanks again!
