### ISSUE TITLE
client.server_serial_number key for windows agent install

### ISSUE THREAD

**Issue by vorsklaa** [google/grr#722]
Not sure if this is classified as an issue or an enhancement but when installing new grr agent on a windows machine if old grr agent was previously installed `client.server_serial_number` key keeps the value of 3 and prevents the new agent from checking in.

Thought process here is that new installer should overwrite or delete `client.server_serial_number` for an easier install.

Note: this is not an issue at all if there are no previous grr client versions installed

**Comment by demonchild2112** [comment]
Persisting the serial number across client version upgrades is by design. Rotating the server key/cert pair is supposed to invalidate old server certificates, as described [here](https://grr-doc.readthedocs.io/en/latest/maintaining-and-tuning/key-management/rotating.html).

If you installed a new server version without re-using existing keys and certificates (this resets the serial number), rotating the server key again with `grr_config_updater rotate_server_key` will increment the serial number so clients can continue talking to the server.
