### ISSUE TITLE
Client Rate not honored for hunts

### ISSUE THREAD

**Issue by keithtyler** [google/grr#728]
Scheduling a hunt at 3 clients per minute results in ~200 clients scheduled in 1 minute. 

I'm running the latest GRR release with 2 worker processes. If you need any logs, let me know!

**Comment by mbushkov** [comment]
Hi @keithtyler! 
Are you using the new relational datastore (REL_DB) or the legacy AFF4?

If you're using REL_DB, this likely an issue with presentation, rather than with the client rate itself. In REL_DB, we do schedule all the flows *immediately* when each client pings the server, but these flows are scheduled *in the future*, according to the client rate. If you check the Hunt Graph tab, you'll likely see that the line indicating "Completed Flows" actually conforms to the client rate of 3. Can you please double check that?

**Comment by keithtyler** [comment]
I'm using REL_DB. Checking the graph tab, client rate is correct. Thank you.
