### ISSUE TITLE
Questions about future GRR plans

### ISSUE THREAD

**Issue by Codehardt** [google/grr#730]
Hi,

I am using GRR 3.1.0.2 on Debian 9 for over 2 years. Soon, I want to upgrade my environment to GRR 3.3.0.4. Instead of using Debian 9 again, my plan is to install GRR on Debian 10. 

In my test environment, GRR 3.3.0.4 installation failed on Debian 10 with `ImportError: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory`. **Are there any near future plans to support Debian 10?**

I also noticed that GRR 3.3.0.4 still uses Python2 (**support ends soon!**) but also noticed that GRR's code contains future imports e.g. for `print(...)` function. **Will one of the next GRR releases upgrade from Python2 to Python3?**

Kind regards,
Marcel

**Comment by clairmont32** [comment]
@Codehardt we saw that error with a fresh install on Ubuntu. We fixed it by ensuring all the python libraries were updated. Have you tried that yet?

**Comment by mbushkov** [comment]
Hi @Codehardt! Thank you for the questions.

First, the practical issue of installing on Debian 10. Our Deb package is built on Ubuntu Xenial which has libssl1.0.0, so GRR is effectively linked against libcrypto.so.1.0.0. Debian 10, on the other hand is shipped with libssl.1.1.0, hence the issue: when you run GRR, it fails to find the libcrypto library version that it was linked against.

An easy way to fix this is to add the following to `/etc/apt/sources.list`:
```
deb http://security.debian.org/debian-security jessie/updates main 
```

And then run:
```
sudo apt-get update
sudo apt-get install libssl1.0.0
```

After that GRR should install without issues. Fundamentally, this issue will resolve itself when we switch from Ubuntu Xenial (16) to Ubuntu Bionic (18) - likely to happen in 2020.

Answering your questions:

1. As [mentioned here](https://grr-doc.readthedocs.io/en/latest/faq.html?highlight=ubuntu#what-operating-system-versions-does-the-server-support), since the release 3.1.0.2 we only support Ubuntu - in a sense that we test our server DEB package and run end to end tests on a stable Ubuntu release (currently - Xenial) and not on another compatible system, i.e. Debian. 

    At the moment we don't have plans to "officially" support Debian 10, due to related maintenance costs. However, most of the time GRR server is very much likely to work on Debian (even, if due to a dependency version discrepancy, a tweak like the one above may be needed).

1. GRR codebase is currently fully Python 3 compatible: all the unit and end-to-end tests are passing on Python 3. The upcoming GRR release will likely be the last Python 2-based release, after that (in a December release) we will fully switch to Python 3.

**Comment by Codehardt** [comment]
Hi @mbushkov ,

thanks for the fast reply. Using an Jessie Backport to install a previous release of libcrypto is no option for me. Instead I created my own build environment to build my own client templates and server debs, using Python 3 and Libcrypto 1.1.
