### ISSUE TITLE
.deb install is missing from most output plugins

### ISSUE THREAD

**Issue by icepaule** [google/grr#771]
Hi all,
while having done a .deb install on Ubuntu 18.0.4, it showed that it's missing most of the output plugins.
How can I add the (i.e. Splunk) missing output plugins that are available from the SRC github.

Thx a lot and over all a fastatic tool to help with forensic actions. Thx for all your contributions.  .-)

Cheers
Marcus

**Comment by max-vogler** [comment]
We have not yet published a release that contains the Splunk OutputPlugin, that's why it is not shown in your installation. We'll publish a release this quarter, then you'll see the OutputPlugin. If you don't want to wait, you can also [install from HEAD](https://grr-doc.readthedocs.io/en/latest/installing-grr-server/from-head-deb.html).

**Comment by icepaule** [comment]
Perfect, I just thought I did something wrong during install.
Thanks a lot for the reply and the help.

Cheers
Marcus
