### ISSUE TITLE
sorry, the application grr_config_updated has stopped unexpectedly.

### ISSUE THREAD

**Issue by techtig** [google/grr#816]
Hi,

I am newbie to Linux. I was trying to install grr server 3.4.2 on ubuntu machine installed on Virtual box. Server was downloaded and nearly finishing installation and at 99% installation get crashed.The crash report is showing the error message as below;

installed grr-server package post-installation script subprocess returned error exit status134
and in the Terminal last 3 lines are

Errors were encountered while processing:
grr-server
E: Sub-process /usr/bin/dpkg returned an error code (1)

please help

**Comment by mbushkov** [comment]
@techtig , which Ubuntu version are you using? What command did you use to install GRR?

**Comment by techtig** [comment]
I am using Ubuntu 20.04.1 LTS and used below link to install grr server

https://grr-doc.readthedocs.io/en/latest/installing-grr-server/from-release-deb.html

**Comment by mbushkov** [comment]
This is likely the issue. Per our [docs](https://grr-doc.readthedocs.io/en/latest/installing-grr-server/from-release-deb.html?highlight=ubuntu#installing-from-a-release-server-deb-recommended): GRR server debs are built for Ubuntu 18.04 Bionic. IIRC GRR server deb won't work on Ubuntu 20 due to Python version incompatibilities.

**Comment by techtig** [comment]
Do you recommend me to go with 18.04??

**Comment by mbushkov** [comment]
> Do you recommend me to go with 18.04??

Yes, correct.
